/**
 * EventPilot AI - Mock Vendor Data
 * Phase 4: Fallback data for vendor research agent
 */

import { Vendor, KpiCategory } from '../db/schema';

export const mockVendorsByCategory: Record<KpiCategory['name'], Omit<Vendor, 'id' | 'kpi_category_id' | 'created_at'>[]> = {
  food_drinks: [
    {
      name: "Gourmet Catering Co.",
      contact_email: "info@gourmetcatering.com",
      contact_phone: "+1-555-0101",
      source: "google",
      rating: 4.8,
      review_count: 342,
      price_estimate: 2500,
      profile_url: "https://example.com/gourmet-catering",
      status: "shortlisted",
    },
    {
      name: "Taco Fiesta Truck",
      contact_email: "bookings@tacofiesta.com",
      contact_phone: "+1-555-0102",
      source: "yelp",
      rating: 4.9,
      review_count: 567,
      price_estimate: 1800,
      profile_url: "https://example.com/taco-fiesta",
      status: "shortlisted",
    },
    {
      name: "Premium Beverage Service",
      contact_email: "events@premiumbev.com",
      contact_phone: "+1-555-0103",
      source: "google",
      rating: 4.7,
      review_count: 234,
      price_estimate: 1200,
      profile_url: "https://example.com/premium-bev",
      status: "shortlisted",
    },
  ],
  
  av_equipment: [
    {
      name: "ProAV Rentals",
      contact_email: "rentals@proav.com",
      contact_phone: "+1-555-0201",
      source: "google",
      rating: 4.9,
      review_count: 189,
      price_estimate: 800,
      profile_url: "https://example.com/proav",
      status: "shortlisted",
    },
    {
      name: "Big Screen Events",
      contact_email: "info@bigscreenevents.com",
      contact_phone: "+1-555-0202",
      source: "yelp",
      rating: 4.8,
      review_count: 156,
      price_estimate: 950,
      profile_url: "https://example.com/bigscreen",
      status: "shortlisted",
    },
    {
      name: "Sound & Vision Pro",
      contact_email: "bookings@soundvision.com",
      contact_phone: "+1-555-0203",
      source: "google",
      rating: 4.6,
      review_count: 98,
      price_estimate: 750,
      profile_url: "https://example.com/soundvision",
      status: "shortlisted",
    },
  ],
  
  merch: [
    {
      name: "Custom Jersey Shop",
      contact_email: "orders@customjersey.com",
      contact_phone: "+1-555-0301",
      source: "amazon",
      rating: 4.7,
      review_count: 1234,
      price_estimate: 600,
      profile_url: "https://example.com/custom-jersey",
      status: "shortlisted",
    },
    {
      name: "Team Spirit Merchandise",
      contact_email: "sales@teamspirit.com",
      contact_phone: "+1-555-0302",
      source: "google",
      rating: 4.8,
      review_count: 445,
      price_estimate: 750,
      profile_url: "https://example.com/team-spirit",
      status: "shortlisted",
    },
    {
      name: "Fan Gear Express",
      contact_email: "info@fangear.com",
      contact_phone: "+1-555-0303",
      source: "amazon",
      rating: 4.5,
      review_count: 892,
      price_estimate: 500,
      profile_url: "https://example.com/fangear",
      status: "shortlisted",
    },
  ],
  
  decor: [
    {
      name: "Event Styling Studio",
      contact_email: "hello@eventstyling.com",
      contact_phone: "+1-555-0401",
      source: "google",
      rating: 4.9,
      review_count: 278,
      price_estimate: 1500,
      profile_url: "https://example.com/event-styling",
      status: "shortlisted",
    },
    {
      name: "Party Perfect Decor",
      contact_email: "bookings@partyperfect.com",
      contact_phone: "+1-555-0402",
      source: "yelp",
      rating: 4.7,
      review_count: 334,
      price_estimate: 1200,
      profile_url: "https://example.com/party-perfect",
      status: "shortlisted",
    },
    {
      name: "Balloon & Banner Co.",
      contact_email: "orders@balloonbanner.com",
      contact_phone: "+1-555-0403",
      source: "google",
      rating: 4.6,
      review_count: 167,
      price_estimate: 800,
      profile_url: "https://example.com/balloon-banner",
      status: "shortlisted",
    },
  ],
  
  venue: [
    {
      name: "Downtown Event Space",
      contact_email: "bookings@downtownevents.com",
      contact_phone: "+1-555-0501",
      source: "google",
      rating: 4.8,
      review_count: 456,
      price_estimate: 3500,
      profile_url: "https://example.com/downtown-events",
      status: "shortlisted",
    },
    {
      name: "Garden Pavilion",
      contact_email: "info@gardenpavilion.com",
      contact_phone: "+1-555-0502",
      source: "yelp",
      rating: 4.9,
      review_count: 389,
      price_estimate: 4000,
      profile_url: "https://example.com/garden-pavilion",
      status: "shortlisted",
    },
    {
      name: "Rooftop Venue 360",
      contact_email: "events@rooftop360.com",
      contact_phone: "+1-555-0503",
      source: "google",
      rating: 4.7,
      review_count: 234,
      price_estimate: 5000,
      profile_url: "https://example.com/rooftop360",
      status: "shortlisted",
    },
  ],
  
  photography: [
    {
      name: "Moments Photography",
      contact_email: "book@momentsphotography.com",
      contact_phone: "+1-555-0601",
      source: "google",
      rating: 4.9,
      review_count: 567,
      price_estimate: 2000,
      profile_url: "https://example.com/moments-photo",
      status: "shortlisted",
    },
    {
      name: "Capture Events Pro",
      contact_email: "info@captureevents.com",
      contact_phone: "+1-555-0602",
      source: "yelp",
      rating: 4.8,
      review_count: 423,
      price_estimate: 1800,
      profile_url: "https://example.com/capture-events",
      status: "shortlisted",
    },
    {
      name: "Lens & Light Studios",
      contact_email: "bookings@lenslight.com",
      contact_phone: "+1-555-0603",
      source: "google",
      rating: 4.7,
      review_count: 312,
      price_estimate: 1500,
      profile_url: "https://example.com/lens-light",
      status: "shortlisted",
    },
  ],
  
  entertainment: [
    {
      name: "DJ Soundwave",
      contact_email: "bookings@djsoundwave.com",
      contact_phone: "+1-555-0701",
      source: "google",
      rating: 4.8,
      review_count: 289,
      price_estimate: 1200,
      profile_url: "https://example.com/dj-soundwave",
      status: "shortlisted",
    },
    {
      name: "Live Band Collective",
      contact_email: "info@livebandcollective.com",
      contact_phone: "+1-555-0702",
      source: "yelp",
      rating: 4.9,
      review_count: 178,
      price_estimate: 2500,
      profile_url: "https://example.com/live-band",
      status: "shortlisted",
    },
    {
      name: "Magic & Comedy Acts",
      contact_email: "bookings@magiccomedy.com",
      contact_phone: "+1-555-0703",
      source: "google",
      rating: 4.7,
      review_count: 145,
      price_estimate: 800,
      profile_url: "https://example.com/magic-comedy",
      status: "shortlisted",
    },
  ],
};

export function getMockVendorsForCategory(categoryName: KpiCategory['name']): Omit<Vendor, 'id' | 'kpi_category_id' | 'created_at'>[] {
  return mockVendorsByCategory[categoryName] || [];
}

// Made with Bob
